In [1]:
import numpy as np

## Data Types & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])


In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
# Number of dimensions of array
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2, 3))

In [18]:
type(ones)

numpy.ndarray

In [19]:
zeroes = np.zeros((2, 3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 4, 8, 4, 5],
       [5, 7, 6, 3, 7],
       [7, 4, 7, 5, 5]])

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [25]:
random_array2 =np.random.random(size=(5, 3))
random_array2

array([[0.33842723, 0.88420587, 0.08366647],
       [0.44009172, 0.80179152, 0.93111997],
       [0.02320332, 0.40888858, 0.06430027],
       [0.42227055, 0.70252486, 0.49812864],
       [0.58933887, 0.62256139, 0.57875352]])

In [26]:
random_array2.shape

(5, 3)

In [27]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.06855018, 0.44858487, 0.11044246],
       [0.74902435, 0.50035298, 0.67444806],
       [0.41609517, 0.64761855, 0.24504114],
       [0.6931957 , 0.49013757, 0.07416821],
       [0.67856533, 0.53848122, 0.20617231]])

In [28]:
# Pseudo-random numbers
np.random.seed(seed=0)