In [2]:
import numpy as np

## Data Types & Attributes

In [3]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])


In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
# Number of dimensions of array
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2, 3))

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeroes = np.zeros((2, 3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[8, 8, 6, 9, 2],
       [7, 7, 8, 6, 6],
       [0, 7, 4, 8, 5]])

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array2 =np.random.random(size=(5, 3))
random_array2

array([[0.98091645, 0.08444668, 0.47564067],
       [0.30864725, 0.34155835, 0.04718079],
       [0.94956108, 0.61617562, 0.98116789],
       [0.84513223, 0.88933721, 0.35240879],
       [0.98195562, 0.49595764, 0.30722473]])

In [26]:
random_array2.shape

(5, 3)

In [27]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.23435627, 0.74004419, 0.70576291],
       [0.87699472, 0.20188455, 0.76504113],
       [0.08571074, 0.32488483, 0.68882225],
       [0.93909436, 0.23523175, 0.46528477],
       [0.64486192, 0.34826884, 0.68536334]])

In [39]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [41]:
#np.random.seed(7)
random_array5 = np.random.random(size=(5, 3))
random_array5

array([[0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561],
       [0.77423369, 0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 , 0.61209572],
       [0.616934  , 0.94374808, 0.6818203 ]])

## 3. Viewing arrays and matrices

In [43]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a1

array([1, 2, 3])

In [45]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [46]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
a1[0]

1

In [48]:
a2[0]

array([1. , 2. , 3.3])

In [49]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
#First two values in array
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [53]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4],
         [6, 5, 8, 2, 3]],

        [[9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2],
         [3, 9, 7, 7, 5]],

        [[1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2],
         [5, 5, 0, 8, 1],
         [1, 0, 3, 8, 8]]],


       [[[4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1],
         [2, 1, 4, 2, 5],
         [5, 5, 2, 5, 7]],

        [[7, 6, 1, 6, 7],
         [2, 3, 1, 9, 5],
         [9, 9, 2, 0, 9],
         [1, 9, 0, 6, 0]],

        [[4, 8, 4, 3, 3],
         [8, 8, 7, 0, 3],
         [8, 7, 7, 1, 8],
         [4, 7, 0, 4, 9]]]])

In [54]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [55]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[1, 6, 8, 8],
         [2, 3, 6, 3],
         [5, 7, 0, 8],
         [6, 5, 8, 2]],

        [[9, 7, 5, 3],
         [5, 3, 3, 7],
         [9, 9, 7, 3],
         [3, 9, 7, 7]],

        [[1, 2, 2, 8],
         [5, 8, 4, 0],
         [5, 5, 0, 8],
         [1, 0, 3, 8]]],


       [[[4, 4, 0, 9],
         [7, 3, 2, 1],
         [2, 1, 4, 2],
         [5, 5, 2, 5]],

        [[7, 6, 1, 6],
         [2, 3, 1, 9],
         [9, 9, 2, 0],
         [1, 9, 0, 6]],

        [[4, 8, 4, 3],
         [8, 8, 7, 0],
         [8, 7, 7, 1],
         [4, 7, 0, 4]]]])

In [56]:
a8 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[10,20,30],[40,50,60],[70,80,90],[11,12,13]],[[11,21,30],[41,51,60],[71,81,90],[11,12,13]],[[12,22,30],[42,52,60],[72,82,90],[11,12,13]]])

In [63]:
a8.shape, a8


((4, 4, 3),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [11, 12, 13]],
 
        [[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90],
         [11, 12, 13]],
 
        [[11, 21, 30],
         [41, 51, 60],
         [71, 81, 90],
         [11, 12, 13]],
 
        [[12, 22, 30],
         [42, 52, 60],
         [72, 82, 90],
         [11, 12, 13]]]))